package com.gdsc.birdsweeper.domain;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "dispenser")
@Entity
public class Dispenser extends AutoGeneratedId implements Serializable {

    @RequiredArgsConstructor
    @Getter
    public enum Status {
        NORMAL("NORMAL"),               // 정상
        NO_FEED("NO_FEED"),             // 먹이없음
        FULL_TRASH("FULL_TRASH"),       // 쓰레기통꽉참
        ERROR_CAMERA("ERROR_CAMERA"),   // 카메라오류
        ERROR_CONNECT("ERROR_CONNECT"); // 통신오류

        private final String value;
    }

    @RequiredArgsConstructor
    @Getter
    public enum SensorStatus {
        NORMAL("NORMAL"),
        ERROR("ERROR");

        private final String value;
    }

    @Column(nullable = false, unique = true, length = 64)
    private String code;

    @Column(length = 128)
    private String location;    // 설치지역(주소)

    @Column(nullable = false, length = 64)
    private String latitude;    // 위도

    @Column(nullable = false, length = 64)
    private String longitude;   // 경도

    @Column(nullable = false, length = 32)
    private Status status;

    @Column(length = 32)
    private Integer feedCnt;

    @Column(length = 32, name = "created_username")
    private String createdUser;

    @CreationTimestamp
    @Column(nullable = false, length = 20, updatable = false)
    private LocalDateTime createdDate;

    @UpdateTimestamp
    @Column
    private LocalDateTime updatedDate;
}
