package com.gdsc.birdsweeper.domain;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "user_dispenser")
@Entity
public class UserDispenser extends AutoGeneratedId implements Serializable {

    @ManyToOne
    @JoinColumn(name = "username")
    private User user;

    @ManyToOne
    @JoinColumn(name = "dispenser_id")
    private Dispenser dispenser;

    @CreationTimestamp
    @Column(nullable = false, length = 20, updatable = false)
    private LocalDateTime createdDate;

    public UserDispenser(User user, Dispenser dispenser) {
        this.user = user;
        this.dispenser = dispenser;
    }
}
